// Do NOT edit this file. It was automatically generated by https://github.com/aviate-labs/agent-go.
import T "types";

import { principalOfBlob } = "mo:⛔";

actor class _registry() : async actor {} {
    public shared func add_api_boundary_nodes(_arg0 : T.AddApiBoundaryNodesPayload) : async () {
        ()
    };
    public shared func add_firewall_rules(_arg0 : T.AddFirewallRulesPayload) : async () {
        ()
    };
    public shared func add_node(_arg0 : T.AddNodePayload) : async (T.Result) {
        (#Ok(principalOfBlob("x65889F698C07D7C894DA1BD5CA17F31F64C27784AB34E28F07F327E15569DFC5")))
    };
    public shared func add_node_operator(_arg0 : T.AddNodeOperatorPayload) : async () {
        ()
    };
    public shared func add_nodes_to_subnet(_arg0 : T.AddNodesToSubnetPayload) : async () {
        ()
    };
    public shared func add_or_remove_data_centers(_arg0 : T.AddOrRemoveDataCentersProposalPayload) : async () {
        ()
    };
    public shared func bless_replica_version(_arg0 : T.BlessReplicaVersionPayload) : async () {
        ()
    };
    public shared func change_subnet_membership(_arg0 : T.ChangeSubnetMembershipPayload) : async () {
        ()
    };
    public shared func clear_provisional_whitelist() : async () {
        ()
    };
    public shared func complete_canister_migration(_arg0 : T.CompleteCanisterMigrationPayload) : async (T.Result1) {
        (#Ok)
    };
    public shared func create_subnet(_arg0 : T.CreateSubnetPayload) : async () {
        ()
    };
    public shared func delete_subnet(_arg0 : T.DeleteSubnetPayload) : async () {
        ()
    };
    public shared func deploy_guestos_to_all_subnet_nodes(_arg0 : T.DeployGuestosToAllSubnetNodesPayload) : async () {
        ()
    };
    public shared func deploy_guestos_to_all_unassigned_nodes(_arg0 : T.DeployGuestosToAllUnassignedNodesPayload) : async () {
        ()
    };
    public query func get_build_metadata() : async (Text) {
        ("16954823083438725750")
    };
    public query func get_node_operators_and_dcs_of_node_provider(_arg0 : Principal) : async (T.Result2) {
        (#Ok([ ( { id = "14850561312921654472"; gps = ?{ latitude = "UNKNOWN" # "float32"; longitude = "UNKNOWN" # "float32" }; region = "8551073967390334963"; owner = "16852795205354512948" }, { ipv6 = ?"11125315087921801557"; node_operator_principal_id = "x755D216CD371311FA94A0A14937936080790ECF3CA9E2E2088B3BEFB840C4C1A"; node_allowance = 2423141441329273866; rewardable_nodes = [ ( "6079560768047329034", 3562109596 ) ]; node_provider_principal_id = "x8EF2EC9B2498F34A2B149A8CF696F708866F3142755366C43EDAECCECEA5BF83"; dc_id = "1505710812436736874" } ) ]))
    };
    public query func get_node_providers_monthly_xdr_rewards() : async (T.Result3) {
        (#Ok({ rewards = [ ( "14850561312921654472", 8551073967390334963 ) ] }))
    };
    public query func get_subnet_for_canister(_arg0 : T.GetSubnetForCanisterRequest) : async (T.Result4) {
        (#Ok({ subnet_id = ?principalOfBlob("x65889F698C07D7C894DA1BD5CA17F31F64C27784AB34E28F07F327E15569DFC5") }))
    };
    public shared func prepare_canister_migration(_arg0 : T.PrepareCanisterMigrationPayload) : async (T.Result1) {
        (#Ok)
    };
    public shared func recover_subnet(_arg0 : T.RecoverSubnetPayload) : async () {
        ()
    };
    public shared func remove_api_boundary_nodes(_arg0 : T.RemoveApiBoundaryNodesPayload) : async () {
        ()
    };
    public shared func remove_firewall_rules(_arg0 : T.RemoveFirewallRulesPayload) : async () {
        ()
    };
    public shared func remove_node_directly(_arg0 : T.RemoveNodeDirectlyPayload) : async () {
        ()
    };
    public shared func remove_node_operators(_arg0 : T.RemoveNodeOperatorsPayload) : async () {
        ()
    };
    public shared func remove_nodes(_arg0 : T.RemoveNodesPayload) : async () {
        ()
    };
    public shared func remove_nodes_from_subnet(_arg0 : T.RemoveNodesPayload) : async () {
        ()
    };
    public shared func reroute_canister_ranges(_arg0 : T.RerouteCanisterRangesPayload) : async (T.Result1) {
        (#Ok)
    };
    public shared func retire_replica_version(_arg0 : T.RetireReplicaVersionPayload) : async () {
        ()
    };
    public shared func revise_elected_replica_versions(_arg0 : T.ReviseElectedGuestosVersionsPayload) : async () {
        ()
    };
    public shared func set_firewall_config(_arg0 : T.SetFirewallConfigPayload) : async () {
        ()
    };
    public shared func update_api_boundary_nodes_version(_arg0 : T.AddApiBoundaryNodesPayload) : async () {
        ()
    };
    public shared func update_elected_hostos_versions(_arg0 : T.UpdateElectedHostosVersionsPayload) : async () {
        ()
    };
    public shared func update_elected_replica_versions(_arg0 : T.ReviseElectedGuestosVersionsPayload) : async () {
        ()
    };
    public shared func update_firewall_rules(_arg0 : T.AddFirewallRulesPayload) : async () {
        ()
    };
    public shared func update_node_directly(_arg0 : T.UpdateNodeDirectlyPayload) : async (T.Result1) {
        (#Ok)
    };
    public shared func update_node_domain_directly(_arg0 : T.UpdateNodeDomainDirectlyPayload) : async (T.Result1) {
        (#Ok)
    };
    public shared func update_node_ipv4_config_directly(_arg0 : T.UpdateNodeIPv4ConfigDirectlyPayload) : async (T.Result1) {
        (#Ok)
    };
    public shared func update_node_operator_config(_arg0 : T.UpdateNodeOperatorConfigPayload) : async () {
        ()
    };
    public shared func update_node_operator_config_directly(_arg0 : T.UpdateNodeOperatorConfigDirectlyPayload) : async () {
        ()
    };
    public shared func update_node_rewards_table(_arg0 : T.UpdateNodeRewardsTableProposalPayload) : async () {
        ()
    };
    public shared func update_nodes_hostos_version(_arg0 : T.UpdateNodesHostosVersionPayload) : async () {
        ()
    };
    public shared func update_ssh_readonly_access_for_all_unassigned_nodes(_arg0 : T.UpdateSshReadOnlyAccessForAllUnassignedNodesPayload) : async () {
        ()
    };
    public shared func update_subnet(_arg0 : T.UpdateSubnetPayload) : async () {
        ()
    };
    public shared func update_subnet_replica_version(_arg0 : T.DeployGuestosToAllSubnetNodesPayload) : async () {
        ()
    };
    public shared func update_unassigned_nodes_config(_arg0 : T.UpdateUnassignedNodesConfigPayload) : async () {
        ()
    };
}
