// Do NOT edit this file. It was automatically generated by https://github.com/aviate-labs/agent-go.
import T "types";

import { principalOfBlob } = "mo:⛔";

actor class icparchive() : async actor {} {
    public query func get_blocks(arg0 : T.GetBlocksArgs) : async (T.GetBlocksResult) {
        (#Err(#BadFirstBlockIndex({ requested_index = 6197789885467376506; first_valid_index = 11539667703195591131 })))
    };
}
