// Do NOT edit this file. It was automatically generated by https://github.com/aviate-labs/agent-go.
module T {
    public type Timestamp = Nat64;
    public type Duration = Nat64;
    public type Subaccount = Blob;
    public type Account = { owner : Principal; subaccount : ?T.Subaccount };
    public type TransferArgs = { from_subaccount : ?T.Subaccount; to : T.Account; amount : Nat; fee : ?Nat; memo : ?Blob; created_at_time : ?T.Timestamp };
    public type TransferError = { #BadFee : { expected_fee : Nat }; #BadBurn : { min_burn_amount : Nat }; #InsufficientFunds : { balance : Nat }; #TooOld; #CreatedInFuture : { ledger_time : T.Timestamp }; #Duplicate : { duplicate_of : Nat }; #TemporarilyUnavailable; #GenericError : { error_code : Nat; message : Text } };
    public type Value = { #Nat : Nat; #Int : Int; #Text : Text; #Blob : Blob };
};
