// Package blob is autogenerated by https://github.com/0x51-dev/upeg. DO NOT EDIT.
package blob

import (
	"github.com/0x51-dev/upeg/parser/op"
)

var (
	Blob  = op.Capture{Name: "Blob", Value: op.OneOrMore{Value: op.Or{Alpha, op.And{'\\', Hex}}}}
	Alpha = op.Capture{Name: "Alpha", Value: op.OneOrMore{Value: op.Or{op.RuneRange{Min: 0x41, Max: 0x5A}, op.RuneRange{Min: 0x61, Max: 0x7A}}}}
	Hex   = op.Capture{Name: "Hex", Value: op.Repeat{Min: 2, Max: 2, Value: op.Or{op.RuneRange{Min: 0x30, Max: 0x39}, op.RuneRange{Min: 0x41, Max: 0x46}, op.RuneRange{Min: 0x61, Max: 0x66}}}}
)
